"""Florida DOR land use code descriptions (partial — only the codes we
touch in this pipeline, plus a broader lookup so unexpected codes aren't
displayed as bare integers)."""

# Source: Florida Dept. of Revenue Real Property Use Codes.
DOR_CODES: dict[int, str] = {
    0: "Vacant Residential",
    1: "Single Family",
    2: "Mobile Home",
    3: "Multi-Family 10+ Units",
    4: "Condominium",
    5: "Cooperative",
    6: "Retirement Home",
    7: "Misc. Residential",
    8: "Multi-Family < 10 Units",
    10: "Vacant Commercial",
    11: "Store, One Story",
    12: "Mixed Use — Store/Office/Residential",
    13: "Department Store",
    14: "Supermarket",
    15: "Regional Shopping Center",
    16: "Community Shopping Center",
    17: "Office Building — One Story",
    18: "Office Building — Multi-Story",
    19: "Professional Services Building",
    20: "Airport, Marine Terminal, Piers",
    21: "Restaurant, Cafeteria",
    22: "Drive-In Restaurant",
    23: "Financial Institution",
    24: "Insurance Company",
    25: "Repair Service Shop",
    26: "Service Station",
    27: "Auto Sales, Repair, Storage",
    28: "Parking Lot",
    29: "Wholesale, Warehouse, Storage",
    30: "Florist, Greenhouse",
    31: "Drive-In Theater",
    32: "Enclosed Theater/Auditorium",
    33: "Nightclub, Lounge, Bar",
    34: "Bowling Alley, Skating Rink, Pool Hall",
    35: "Tourist Attraction",
    36: "Camp",
    37: "Racetrack",
    38: "Golf Course",
    39: "Motel/Hotel",
    40: "Vacant Industrial",
    41: "Light Manufacturing",
    42: "Heavy Manufacturing",
    43: "Lumber Yard, Sawmill, Planing Mill",
    44: "Packing Plant",
    45: "Cannery, Fruit Packing",
    46: "Other Food Processing",
    47: "Mineral Processing",
    48: "Warehouse, Distribution Terminal",
    49: "Open Storage",
    70: "Vacant Institutional",
    71: "Churches",
    72: "Private Schools and Colleges",
    73: "Privately Owned Hospital",
    74: "Homes for the Aged",
    75: "Orphanages, Non-Profit Service",
    76: "Mortuary, Cemetery, Crematorium",
    77: "Club, Lodge, Union Hall",
    78: "Sanitarium, Convalescent Home",
    79: "Cultural Organization, Museum",
    80: "Undefined/Reserved",
    82: "Forest, Park, Recreational Area",
    83: "Public County School",
    84: "College (Public)",
    85: "Hospital (Public)",
    86: "County/State/Federal Property",
    89: "Municipal Property Other than for Public Use",
    90: "Government Leasehold Interests",
    91: "Utility",
    92: "Mining/Petroleum/Gas Lands",
    93: "Subsurface Rights",
    94: "Right of Way",
    95: "Rivers, Lakes, Submerged Lands",
    96: "Sewage Disposal, Landfill",
    97: "Outdoor Recreational or Parkland",
    98: "Centrally Assessed",
    99: "Non-Agricultural Acreage",
}


def describe(code) -> str:
    try:
        n = int(code)
    except (TypeError, ValueError):
        return ""
    return DOR_CODES.get(n, f"DOR use code {n}")
